language: ruby
cache: bundler
sudo: false
gemfile: fixture/gemfile

rvm:
  - 2.1
  - 2.2

env:
  - CHEF_VERSION=master
  - CHEF_VERSION=12.5.1
  - CHEF_VERSION=12.4.1
  - CHEF_VERSION=12.3.0
  - CHEF_VERSION=12.2.1
  - CHEF_VERSION=12.1.2
  - CHEF_VERSION=12.0.3
  - CHEF_VERSION=11.18.12
  - CHEF_VERSION=11.16.4
  - CHEF_VERSION=11.14.6
  - CHEF_VERSION=11.12.8
  - CHEF_VERSION=11.10.4
  - CHEF_VERSION=11.8.2
  - CHEF_VERSION=11.6.2
  - CHEF_VERSION=11.4.4
  - CHEF_VERSION=11.2.0
  - CHEF_VERSION=11.0.0

matrix:
  fast_finish: true
  exclude:
    - env: CHEF_VERSION=11.8.2
      rvm: 2.2
    - env: CHEF_VERSION=11.6.2
      rvm: 2.2
    - env: CHEF_VERSION=11.4.4
      rvm: 2.2
    - env: CHEF_VERSION=11.2.0
      rvm: 2.2
    - env: CHEF_VERSION=11.0.0
      rvm: 2.2

  allow_failures:
    - env: CHEF_VERSION=master

script:
  - cd fixture
  - bundle exec knife cookbook doc . -o README-generated.md -c knife.rb
  - diff README-expected.md README-generated.md && rm README-generated.md
